### ISSUE TITLE
Wrapped share button shows even if sharing would not work

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/nucleoid-stats#9]
Unfortunately `navigator.share` has pretty bad [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility), so on some platforms, the share button at the bottom of the wrapped page has no effect. Could a workaround be implemented for platforms that do not have `navigator.share` or fail `navigator.canShare`?

**Comment by ashhhleyyy** [comment]
I'll see if I can gate it behind whether navigator.share is present, the main compatibility issue seems to be desktop firefox though, all the mobile and other desktop browsers support it in latest versions

**Comment by ashhhleyyy** [comment]
related: #10

**Comment by ashhhleyyy** [comment]
Fixed by f6ee6f4
